#!/bin/bash

set -e

echo "Allowing ipv6 forwarding via sysctl"
sysctl net.ipv6.conf.default.forwarding=1
sysctl net.ipv6.conf.all.forwarding=1

echo "General sysctl tweaks"
sysctl vm.swappiness=0
sysctl vm.dirty_ratio=6
sysctl vm.dirty_background_ratio=3

# Default Socket Receive Buffer
sysctl net.core.rmem_default=31457280

# Maximum Socket Receive Buffer
sysctl net.core.rmem_max=33554432

# Default Socket Send Buffer
sysctl net.core.wmem_default=31457280

# Maximum Socket Send Buffer
sysctl net.core.wmem_max=33554432

# Increase number of incoming connections
sysctl net.core.somaxconn=65535

# Increase number of incoming connections backlog
sysctl net.core.netdev_max_backlog=65536

# Increase the maximum amount of option memory buffers
sysctl net.core.optmem_max=25165824

# Increase the maximum total buffer-space allocatable
# This is measured in units of pages (4096 bytes)
sysctl "net.ipv4.tcp_mem=786432 1048576 26777216"
sysctl "net.ipv4.udp_mem=65536 131072 262144"

# Increase the read-buffer space allocatable
sysctl "net.ipv4.tcp_rmem=8192 87380 33554432"
sysctl net.ipv4.udp_rmem_min=16384

# Increase the write-buffer-space allocatable
sysctl "net.ipv4.tcp_wmem=8192 65536 33554432"
sysctl net.ipv4.udp_wmem_min=16384

# ./telegram-bot-api --api-id=29425223 --api-hash=2337e005abc36d32f0c6b679ce81def9 --http-port=8080

# curl -F chat_id="975596313" -F audio=@"output.mp3" http://localhost:8080/bot5057738440:AAHQwgan-2eG3VA1Ir9PkM3Y9LTdyMun4kQ/sendAudio

# curl -F chat_id="975596313" -F video=@"vid.mp4" dVideo && rm vid.mp4

# python -m youtube_dl -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' -o "vid.mp4" --merge-output-format mp4 "https://www.youtube.com/watch?v=CEZ3WEdNS-c" && curl -F chat_id="975596313" -F video=@"vid.mp4" http://localhost:8080/bot5057738440:AAHQwgan-2eG3VA1Ir9PkM3Y9LTdyMun4kQ/sendVideo && rm vid.mp4 

# curl -X GET "http://localhost:8080/bot5057738440:AAHQwgan-2eG3VA1Ir9PkM3Y9LTdyMun4kQ/sendMessage?chat_id=975596313&text=Hello, Dhanush"

# /data/telegram-youtube-video-uploader/yt

# *       *       *       *       *       /data/telegram-youtube-video-uploader/yt/text.sh >> /data/telegram-youtube-video-uploader/yt/cron.log :


